### ISSUE TITLE
Error CS0246 The type or namespace name 'ProfilerColumn' could not be found (are you missing a using directive or an assembly reference?) SnappyProfilerViewer.cs 34

### ISSUE THREAD

**Issue by naviln** [AquaGeneral/Snappy-Profiler-Viewer#1]
Hey buddy, 

Are you still supporting this? I tried to use it in Unity 2019.2.21f1, since the default profiler is so slow.

Unfortunately getting a handful of errors like:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'ProfilerColumn' does not exist in the current context	Assembly-CSharp-Editor	C:\dev\xChangeMobileBorrower\xChangeBorrower\Assets\Editor\SnappyProfilerViewer.cs	369	Active
`

Any ideas on how to resolve?

Cheers!
Navil

**Comment by AquaGeneral** [comment]
It looks like Unity Technologies have refactored the profiler stuff alot. 

At least with the error you metioned, they killed off the ProfilerColumn and instead replaced it with inidividual constants as seen here: https://github.com/Unity-Technologies/UnityCsReference/blob/2019.2/Modules/ProfilerEditor/Public/ProfilerFrameDataView.bindings.cs#L31

I haven't looked into it, but maybe all you'd have to do would be find what Unity have changed by looking at the UnityCSReference code. Easier said than done of course :) There's a chance a whole lot has changed and might require a large refactor or even rewrite.

It really sucks that the profiler still lags. If I have any troubles with it myself in the future I will probably reboot this project if it's similar in scope.

Let me know if you need anything else!

**Comment by naviln** [comment]
The profiler started behaving again, through some strange miracle.
Thanks for the response though!
